name = "sveltekit-workers-template"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-03"
[site]
bucket = './build'
entry-point = './workers-site'
